spring:
  application:
    name: taskmate

  datasource:
    url: jdbc:h2:mem:taskmate;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop   # Auto-create/drop tables for H2 in-memory
    show-sql: true
    properties:
        hibernate:
          format_sql: true

  sql:
    init:
      mode: always     # Always run schema.sql on startup
      schema-locations: classpath:schema.sql
#      continue-on-error: false
