spring:
  application:
    name: taskmate

  datasource:
    url: jdbc:postgresql://localhost:5432/taskmate
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate   # IMPORTANT â†’ prevents Hibernate from auto-creating tables
    show-sql: true
    properties:
        hibernate:
          format_sql: true
        type:
          preferred_enum_type: pg_enum

  sql:
    init:
      mode: never     # Forces schema.sql to run
#      continue-on-error: false
